#!/usr/bin/env bash
# scripts/capture_evidence.sh — regenerate the acceptance-gate evidence log.
#
# Runs the mandatory gates and captures output into
# docs/evidence/GATE_EVIDENCE.md so reviewers can verify the last-known-good
# state. Re-run this after any release/checkpoint.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs/evidence/GATE_EVIDENCE.md"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ALLOW_DIRTY=0

# shellcheck disable=SC1091
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

if [ "${1:-}" = "--allow-dirty" ]; then
  ALLOW_DIRTY=1
  shift
fi
if [ "$#" -ne 0 ]; then
  echo "usage: $0 [--allow-dirty]" >&2
  exit 2
fi

is_dirty() {
  git diff --quiet --no-ext-diff &&
    git diff --cached --quiet --no-ext-diff &&
    [ -z "$(git ls-files --others --exclude-standard)" ]
}

DIRTY_STATUS="clean"
if ! is_dirty; then
  DIRTY_STATUS="dirty"
  if [ "$ALLOW_DIRTY" -ne 1 ]; then
    echo "refusing evidence capture from a dirty tree; use --allow-dirty for research evidence" >&2
    exit 2
  fi
fi

HEAD="$(git rev-parse HEAD 2>/dev/null || printf 'unknown')"
BRANCH="$(git symbolic-ref --short -q HEAD 2>/dev/null || printf 'detached')"
TAG="$(git describe --tags --exact-match HEAD 2>/dev/null || printf 'none')"
LOCK_HASH="$(sha256sum Cargo.lock 2>/dev/null | awk '{print $1}' || printf 'unavailable')"
RUSTC_VERSION="$(rustc -V 2>/dev/null || printf 'unavailable')"
CARGO_VERSION="$(cargo -V 2>/dev/null || printf 'unavailable')"
HOST_TARGET="$(rustc -vV 2>/dev/null | awk '/^host:/ {print $2}' || printf 'unavailable')"
OS_INFO="$(uname -srv 2>/dev/null || printf 'unavailable')"

mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp)"
TEST_LOG="$(mktemp)"
DEMO_LOG="$(mktemp)"
OVERALL_RC=0
trap 'rm -f "$TMP" "$TEST_LOG" "$DEMO_LOG"' EXIT

record_status() {
  local rc="$1"
  if [ "$rc" -ne 0 ]; then
    OVERALL_RC=1
  fi
}

sanitize_output() {
  sed \
    -e "s|$ROOT|<repository>|g" \
    -e "s|$HOME|<home>|g"
}

run_compact_gate() {
  local title="$1"
  shift
  local log rc
  log="$(mktemp)"
  "$@" >"$log" 2>&1
  rc=$?
  echo
  echo "## $title"
  echo
  echo '```'
  if [ "$rc" -eq 0 ]; then
    tail -3 "$log" | sanitize_output
  else
    sanitize_output <"$log"
  fi
  echo "[exit $rc]"
  echo '```'
  rm -f "$log"
  record_status "$rc"
}

run_test_gate() {
  local rc
  cargo test --workspace --locked >"$TEST_LOG" 2>&1
  rc=$?
  echo
  echo "## test (workspace)"
  echo
  echo '```'
  grep -E "test result:|Running" "$TEST_LOG" | sanitize_output || true
  if [ "$rc" -ne 0 ]; then
    echo
    echo "--- failing test command output ---"
    sanitize_output <"$TEST_LOG"
  fi
  echo "[exit $rc]"
  echo '```'
  record_status "$rc"
}

run_demo_gate() {
  local rc
  ./scripts/demo.sh all >"$DEMO_LOG" 2>&1
  rc=$?
  echo
  echo "## demo (all)"
  echo
  echo '```'
  if [ "$rc" -eq 0 ]; then
    grep -E "DEMO|EXPECT|demo complete|Payload:|Sent bytes:|exit code:" "$DEMO_LOG" || true
  else
    sanitize_output <"$DEMO_LOG"
  fi
  echo "[exit $rc]"
  echo '```'
  record_status "$rc"
}

# Capture the test totals by summing parsed "N passed" / "N failed" counts.
capture_totals() {
  local passed=0 failed=0 ignored=0
  local result_lines=0
  while read -r line; do
    result_lines=$((result_lines + 1))
    local p f i
    p=$(printf '%s\n' "$line" | awk '{for (i=1; i<=NF; i++) if ($i == "passed;") {print $(i-1); exit}}')
    f=$(printf '%s\n' "$line" | awk '{for (i=1; i<=NF; i++) if ($i == "failed;") {print $(i-1); exit}}')
    i=$(printf '%s\n' "$line" | awk '{for (i=1; i<=NF; i++) if ($i == "ignored;") {print $(i-1); exit}}')
    passed=$((passed + ${p:-0}))
    failed=$((failed + ${f:-0}))
    ignored=$((ignored + ${i:-0}))
  done < <(grep -E '^test result:' "$TEST_LOG" || true)
  echo
  echo "## totals"
  echo
  echo '```'
  echo "PASSED=$passed  FAILED=$failed  IGNORED=$ignored"
  echo "RESULT_LINES=$result_lines"
  echo '```'
  if [ "$result_lines" -eq 0 ]; then
    echo "ERROR: cargo test produced no test-result lines"
    OVERALL_RC=1
  fi
}

{
  echo "# SHPH Acceptance-Gate Evidence"
  echo
  echo "Auto-generated by \`scripts/capture_evidence.sh\`. Do not hand-edit;"
  echo "re-run the script to refresh. Last captured: **$TS** (UTC)."
  echo
  echo "## provenance"
  echo
  echo '```'
  echo "commit=$HEAD"
  echo "branch=$BRANCH"
  echo "tag=$TAG"
  echo "tree=$DIRTY_STATUS"
  echo "cargo_lock_sha256=$LOCK_HASH"
  echo "rustc=$RUSTC_VERSION"
  echo "cargo=$CARGO_VERSION"
  echo "target=$HOST_TARGET"
  echo "os=$OS_INFO"
  echo '```'
  run_compact_gate "fmt" cargo fmt --all -- --check
  run_compact_gate "clippy (warnings = errors)" cargo clippy --workspace --all-targets --locked -- -D warnings
  run_test_gate
  capture_totals
  run_compact_gate "reproducible build (--locked)" cargo build --workspace --locked
  run_demo_gate
  echo
  echo "## overall"
  echo
  echo '```'
  echo "[exit $OVERALL_RC]"
  echo '```'
} >"$TMP" 2>&1

mv -f "$TMP" "$OUT"

echo ">> wrote $OUT"
exit "$OVERALL_RC"
