#!/usr/bin/env bash
# scripts/capture_evidence.sh — regenerate the acceptance-gate evidence log.
#
# Runs the mandatory gates and captures output into
# docs/evidence/GATE_EVIDENCE.md so reviewers can verify the last-known-good
# state. Re-run this after any release/checkpoint.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs/evidence/GATE_EVIDENCE.md"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# shellcheck disable=SC1091
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Run a gate; capture exit code but never abort (so all gates are reported).
run_gate() {
  echo
  echo "## $1"
  echo
  echo '```'
  shift
  set +e
  "$@"
  local rc=$?
  set -e
  echo "[exit $rc]"
  echo '```'
  return 0
}

# Capture the test totals by summing parsed "N passed" / "N failed" counts.
capture_totals() {
  set +e
  cargo test --workspace 2>&1 | grep -E '^test result:' > "$TMP"
  set -e
  local passed=0 failed=0 ignored=0
  while read -r line; do
    local p f i
    p=$(printf '%s' "$line" | sed -n 's/.*\([0-9][0-9]*\) passed.*/\1/p')
    f=$(printf '%s' "$line" | sed -n 's/.*\([0-9][0-9]*\) failed.*/\1/p')
    i=$(printf '%s' "$line" | sed -n 's/.*\([0-9][0-9]*\) ignored.*/\1/p')
    passed=$((passed + ${p:-0}))
    failed=$((failed + ${f:-0}))
    ignored=$((ignored + ${i:-0}))
  done < "$TMP"
  echo
  echo "## totals"
  echo
  echo '```'
  echo "PASSED=$passed  FAILED=$failed  IGNORED=$ignored"
  echo '```'
}

{
  echo "# SHPH Acceptance-Gate Evidence"
  echo
  echo "Auto-generated by \`scripts/capture_evidence.sh\`. Do not hand-edit;"
  echo "re-run the script to refresh. Last captured: **$TS** (UTC)."
  echo
  echo "## fmt"
  echo
  echo '```'
  cargo fmt --all -- --check && echo "[exit 0]" || echo "[non-zero — GATE FAILED]"
  echo '```'
  echo
  echo "## clippy (warnings = errors)"
  echo
  echo '```'
  cargo clippy --workspace --all-targets -- -D warnings 2>&1 | tail -3
  echo '```'
  echo
  echo "## test (workspace)"
  echo
  echo '```'
  cargo test --workspace 2>&1 | grep -E "test result:|Running"
  echo '```'
  capture_totals
  echo
  echo "## reproducible build (--locked)"
  echo
  echo '```'
  cargo build --workspace --locked 2>&1 | tail -2
  echo '```'
} > "$OUT" 2>&1

echo ">> wrote $OUT"
